version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: vkbotpass
      POSTGRES_DB: vk-inter-bot
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

  main_service:
    container_name: main_service_container
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: "postgresql://admin:postgres@postgres:5432/vkbotpass"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: